// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Uo78DPkZ6cXp5FkyJo0-mQ36xHAl1tg',
    appId: '1:345712444130:web:1e250bf96f92ea2d4ed4bb',
    messagingSenderId: '345712444130',
    projectId: 'traningflutterapp',
    authDomain: 'traningflutterapp.firebaseapp.com',
    storageBucket: 'traningflutterapp.appspot.com',
    measurementId: 'G-8ZW9D2DZF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeauNvcsKjuvBmwdhLWMLcL_RPULDGGh8',
    appId: '1:345712444130:android:850012a576a53df54ed4bb',
    messagingSenderId: '345712444130',
    projectId: 'traningflutterapp',
    storageBucket: 'traningflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCMojiCSl2AQjZ9wsMVjXI8QoGzQJoUNY',
    appId: '1:345712444130:ios:6492768dd43e42d94ed4bb',
    messagingSenderId: '345712444130',
    projectId: 'traningflutterapp',
    storageBucket: 'traningflutterapp.appspot.com',
    iosClientId: '345712444130-ihh2ecbimlje5oeejvnqe5tgbalcg88b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCMojiCSl2AQjZ9wsMVjXI8QoGzQJoUNY',
    appId: '1:345712444130:ios:6492768dd43e42d94ed4bb',
    messagingSenderId: '345712444130',
    projectId: 'traningflutterapp',
    storageBucket: 'traningflutterapp.appspot.com',
    iosClientId: '345712444130-ihh2ecbimlje5oeejvnqe5tgbalcg88b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
